version: "3.8"

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '81:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ginproject-network

  gateway-app:
    build:
      context: ../frontend/gateway-app
      dockerfile: Dockerfile
    container_name: gateway-app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - ginproject-network

  app1:
    build:
      context: ../frontend/app1
      dockerfile: Dockerfile
    container_name: app1
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - ginproject-network

  app2:
    build:
      context: ../frontend/app2
      dockerfile: Dockerfile
    container_name: app2
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - ginproject-network

networks:
  ginproject-network:
    external: true
