version: "3.8"

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - '81:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ginproject-network

  gateway-app:
    build:
      context: ../frontend/gateway-app
      dockerfile: Dockerfile
    container_name: gateway-app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - ginproject-network

  fe-app1:
    build:
      context: ../frontend/app1
      dockerfile: Dockerfile
    container_name: fe-app1
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - ginproject-network

  fe-app2:
    build:
      context: ../frontend/app2
      dockerfile: Dockerfile
    container_name: fe-app2
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - ginproject-network

  be-app1:
    build:
      context: ../backend/app1
    container_name: be-app1
    networks:
      - ginproject-network

  be-app2:
    build:
      context: ../backend/app2
    container_name: be-app2
    networks:
      - ginproject-network
    depends_on:
      - be-app1

networks:
  ginproject-network:
    external: true
